pipeline { 
    environment { 
        registry = "tud7/caltech-devops-proj1" 
	registryCredential = 'dockerhub' 
        dockerImage = '' 
    }
    agent any 
    stages { 
        stage('Cloning from GitHub') { 
            steps { 
                git 'https://github.com/tud7/dockerizing-jenkins-pipeline-demo.git' 
            }
        } 
        stage('Build Docker Image') { 
            steps { 
                script { 
                    dockerImage = docker.build(registry + ":$BUILD_NUMBER")
                }
            } 
        }
        stage('Deploy our image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        } 
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $registry:$BUILD_NUMBER" 
            }
        } 
    }
}
